### ISSUE TITLE
SQL Join Request returns visits before March 1st, 2024 and the result doesn't include Cat Owners' name 

### ISSUE THREAD

**Issue by rodikno** [tetiana-qa7/QA_Automation_Java#4]
https://github.com/tetiana-qa7/QA_Automation_Java/blob/5e2f14f55153679c07c472a11d3320e6e8d34b53/HW4_SQL/request.sql#L8

Hi @tetiana-qa7 !

There're some issues with the query you provided:

1. The visits are returned, but including the visits which happened **before** 1st of March 2024
2. The returned joined table doesn't include any information about owners of the cats

```sql
SELECT VisitDate, Reason, Diagnosis, Treatment, Cats.Name, Breed FROM Cats
JOIN Visits
ON Cats.CatID = Visits.CatID
JOIN MedicalRecords
ON Visits.VisitID = MedicalRecords.VisitID
WHERE visitDate > 2024-03-01;
```

![image](https://github.com/tetiana-qa7/QA_Automation_Java/assets/16562135/28b72a2d-e282-49d3-9631-c509b65c6374)

Please investigate the reason -> the general idea is good, although the query needs to be modified a bit to return the expected result
Hint: think about the relations between Visit, MedicalRecord, Cat and Owner -> who owns what and what should be a JOIN chain the query

**Comment by tetiana-qa7** [comment]
thanks, I updated the query and committed it

SELECT VisitDate, Reason, Diagnosis, Treatment, Cats.Name AS catName, Breed, Owners.name AS ownerName, Owners.phone  FROM Owners
JOIN Cats
ON Owners.OwnerID = Cats.OwnerID
JOIN Visits
ON Cats.CatID = Visits.CatID
JOIN MedicalRecords
ON Visits.VisitID = MedicalRecords.VisitID
WHERE visitDate > '2024-03-01';

**Comment by rodikno** [comment]
@tetiana-qa7 this one looks perfect, thanks for the fix!

**Comment by rodikno** [comment]
Issue closed after code rework
